name: weatherapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  geolocator: ^14.0.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/weather/
    - assets/fonts/

  # Custom fonts configuration
  # fonts:
  #   - family: WeatherFont
  #     fonts:
  #       - asset: assets/fonts/weather/WeatherFont-Regular.ttf
  #       - asset: assets/fonts/weather/WeatherFont-Bold.ttf
  #         weight: 700
